isAWS: false

replicaCount: 1

image:
  repository: 172.21.101.81:32000/dedi-service
  pullPolicy: IfNotPresent
  tag: "latest"

serviceAccount:
  name: ""

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 512Mi

autoscaling:
  enabled: false
