isAWS: true

replicaCount: 1

image:
  repository: 082675554211.dkr.ecr.ap-northeast-2.amazonaws.com/api-service
  pullPolicy: IfNotPresent
  tag: "v0.2.0"

service:
  type: ClusterIP
  port: 8181
  targetPort: 8001

containerPort: 8001

config:            
  jwtTimeout: 15      # Minute
  logLevel: "stage"   # dev, stage, prod

serviceAccount:
  name: ""

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 512Mi

autoscaling:
  enabled: false
