isAWS: false

replicaCount: 1

image:
  repository: 172.21.101.61:32000/dedi-agency
  pullPolicy: IfNotPresent
  tag: ""

config:            
  REGION: "DEV"
  RUNENV: "DEV"
  NATS: "172.21.101.201:4222"
  logLevel: "dev"   # dev, stage, prod

serviceAccount:
  name: ""

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 512Mi

autoscaling:
  enabled: false

service:
  type: NodePort
  port: 8222
  targetport: 8222