apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
  creationTimestamp: 2023-12-15T17:40:00Z
data:
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}