apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
  creationTimestamp: 2023-10-15T17:40:00Z
data:
  JWT_TIMEOUT: {{ .Values.config.jwtTimeout | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}