apiVersion: v1
kind: Service
metadata:
  name: {{ include "api-service.fullname" . }}
  labels: {{- include "api-service.labels" . | nindent 4 }}
spec:
  sessionAffinity: ClientIP # For Websocket Session
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector: {{- include "api-service.selectorLabels" . | nindent 4 }}

