apiVersion: v1
kind: Service
metadata:
  name: {{ include "kpi-service.fullname" . }}
  labels:
    {{- include "kpi-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}      
  selector:
    {{- include "kpi-service.selectorLabels" . | nindent 4 }}
