isAWS: false

replicaCount: 1

image:
  repository: 172.21.101.91:32000/user-service
  pullPolicy: IfNotPresent
  tag: "latest"


# pvc:
#   name: "json-data"
#   mountPath: "/mnt/data/json"
#   claimName: "pvc-svc-json"

serviceAccount:
  name: ""

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 512Mi

autoscaling:
  enabled: false

