isAWS: false

replicaCount: 1

image:
  repository: 172.21.101.91:32000/backoffice-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8481
  targetPort: 8401

containerPort: 8401

config:            
  jwtTimeout: 30    # Minute
  logLevel: "dev"   # dev, stage, prod

pvc:
  name: "json-data"
  mountPath: "/mnt/data/json"
  claimName: "pvc-svc-json"

serviceAccount:
  name: ""

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 512Mi

autoscaling:
  enabled: false
