isAWS: false

replicaCount: 1
terminationSeconds: 120

image:
  repository: 172.21.101.91:32000/mail-service
  pullPolicy: IfNotPresent
  tag: "latest"

config:            
  logLevel: "dev"   # dev, stage, prod
  
serviceAccount:
  name: ""

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 512Mi

autoscaling:
  enabled: false
