isAWS: true

replicaCount: 1

image:
  repository: 082675554211.dkr.ecr.ap-northeast-2.amazonaws.com/api-service
  pullPolicy: IfNotPresent
  tag: "v0.3.0"

service:
  type: ClusterIP
  port: 8181
  targetPort: 8001

containerPort: 8001

config:            
  jwtTimeout: 10      # Minute
  logLevel: "prod"   # dev, stage, prod
  
serviceAccount:
  name: ""

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 512Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
