apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
  creationTimestamp: 2023-08-02T10:00:00Z
data:
  MQ_URL: {{ .Values.config.mqURL | quote }}
  LB_IP: {{ .Values.config.lbIP | quote }}  
  JWT_TIMEOUT: {{ .Values.config.jwtTimeout | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}