apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
  creationTimestamp: 2023-10-15T17:40:00Z
data:
  BLACKSTIGMA_REGION: {{ .Values.config.REGION | quote }}
  BLACKSTIGMA_RUNENV: {{ .Values.config.RUNENV | quote }}
  BLACKSTIGMA_NATS: {{ .Values.config.NATS | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}