apiVersion: v1
kind: Service
metadata:
  name: {{ include "dedi-agency.fullname" . }}
  labels: {{- include "dedi-agency.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "dedi-agency.labels" . | nindent 4 }}    