apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
  namespace: {{ .Release.Namespace }}
  creationTimestamp: 2023-10-15T17:40:00Z
data:
  MAX_ROOM:  {{ .Values.config.maxRoom | quote }}
  MAX_PLAYER:  {{ .Values.config.maxPlayer | quote }}
  DEFAULT_CHAN_SIZE:  {{ .Values.config.defaultChanSize | quote }}