apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gyun-service.fullname" . }}
  labels:
    {{- include "gyun-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gyun-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gyun-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "gyun-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            capabilities:
              add:
              - SYS_RESOURCE
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-configmap
          - secretRef:
              name: bs-common-secret
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          # command: ["/bin/bash", "-c", "ulimit -c unlimited"]
          volumeMounts:
          - name: coredump
            mountPath: /var/crash
      #     lifecycle:
      #       preStop:
      #         exec:
      #           command: ["/bin/bash", "-c", "sleep 10"]  
      # terminationGracePeriodSeconds: 30
      volumes:
      - name: coredump
        hostPath:
          path: /var/coredump
          type: Directory
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
