{{ if eq .Values.deploy "rollout" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cb-bridge.fullname" . }}-green
  labels:
    {{- include "cb-bridge.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}      
  selector:
    {{- include "cb-bridge.selectorLabels" . | nindent 4 }}
{{ end }}