isAWS: false

replicaCount: 1

image:
  repository: 172.21.101.61:32000/api-service
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8181
  targetPort: 8001

containerPort: 8001

config:            
  jwtTimeout: 20    # Minute
  logLevel: "dev"   # dev, stage, prod
  
serviceAccount:
  name: ""

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: false
