isAWS: false

replicaCount: 1

image:
  repository: 172.21.101.91:32000/gyun-service
  pullPolicy: IfNotPresent
  tag: "latest"

config:            
  logLevel: "dev"   # dev, stage, prod
  
serviceAccount:
  name: ""

podAnnotations:
  sidecar.istio.io/inject: "false"

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 512Mi
    core: "infinity"

autoscaling:
  enabled: false

securityContext:
  sysctls:
  - name: core
    value: "-1"

# podSecurityContext:
#   sysctls:
#     - name: kernel.core_pattern
#       value: "/var/crash/coredump_%e_%t"
#     - name: kernel.core_pipe_limit
#       value: "0"
#     - name: fs.suid_dumpable
#       value: "2"